spring:
  application:
    name: apirest

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.136:3306/apijava?useTimezone=true&serverTimezone=UTC
    username: apijava_user
    password: SenhaForteAqui

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        # Ajustado para MySQL, já que seu driver é MySQL
        #dialect: org.hibernate.dialect.MariaDBDialect   
logging:
  level:
    root: WARN
    com.digitalmindkr.apirest: DEBUG